[config]
skip_core_tasks = true
unstable_features = ["CTRL_C_HANDLING"]

[tasks.gen_images]
script = """
mkdir -p ./images
../../utils/gen_model_image.sh ./main.scad ./images/main.png
"""

[tasks.gen_stls]
script = """
mkdir -p ./build
../../utils/gen_model_stl.sh ./main.scad ./build/dell_t420_525_bay_drive_bracket.stl
"""

[tasks.watch]
script = "../../utils/watch_in_openscad.sh ./main.scad"
