[config]
skip_core_tasks = true
unstable_features = ["CTRL_C_HANDLING"]

[tasks.gen_images]
script = """
mkdir -p ./images
../../utils/gen_model_image.sh ./main.scad ./images/main.png
"""

[tasks.gen_stls]
script = """
SED=sed; if command -v gsed &> /dev/null; then SED=gsed; fi
VERSION="v$("${SED}" -n 's@^ *MODEL_VERSION *= *"\\([0-9]\\(\\.[0-9]\\)*\\)"; *$@\\1@p' ./main.scad)"

mkdir -p ./build
../../utils/gen_model_stl.sh ./main.scad ./build/dell_t420_525_bay_drive_bracket_"${VERSION}".stl
"""

[tasks.watch]
script = "../../utils/watch_in_openscad.sh ./main.scad"
