[config]
skip_core_tasks = true
unstable_features = ["CTRL_C_HANDLING"]

[tasks.init_git_hooks]
script = """
# NOTE: Tim Apple cognitive tax
LN=ln; if command -v gln &> /dev/null; then LN=gln; fi

"${LN}" -srf ./.hooks/pre-commit ./.git/hooks/pre-commit
"""

[tasks.gen_models_images]
script = """
for model_dir in ./models/*; do
    mkdir -p "${model_dir}/.github"
    ./utils/gen_model_image.sh "${model_dir}/main.scad" "${model_dir}/.github/model_image.png"
done
"""

[tasks.update_readme_models_table]
script = "./utils/gen_models_md_table.py ./models | ./utils/replace_md_file_section.py ./README.md 'Models'"

[tasks.watch_dell_t420_525_bay_drive_bracket]
script = "./utils/watch_in_openscad.sh ./models/dell_t420_525_bay_drive_bracket/main.scad"

[tasks.watch_ikea_satsumas_pot]
script = "./utils/watch_in_openscad.sh ./models/ikea_satsumas_pot/main.scad"
