[config]
skip_core_tasks = true
unstable_features = ["CTRL_C_HANDLING"]

[tasks.gen_models_dists]
script = """
for model_dir in ./models/*; do
  cargo make --cwd "${model_dir}" gen_dist
done
"""

[tasks.gen_models_images]
script = """
for model_dir in ./models/*; do
  cargo make --cwd "${model_dir}" gen_images
done
"""

[tasks.gen_models_stls]
script = """
for model_dir in ./models/*; do
  cargo make --cwd "${model_dir}" gen_stls
done
"""

[tasks.init_git_hooks]
script = """
LN=ln; if command -v gln &> /dev/null; then LN=gln; fi

"${LN}" -srf ./.hooks/pre-commit ./.git/hooks/pre-commit
"""

[tasks.update_readme_models_table]
script = "./utils/gen_models_md_table.py ./models | ./utils/replace_md_file_section.py ./README.md 'Models'"

