// NOTE: In practice, it is recommended to increase depth/height/width measurements by at least 1 to
// avoid issues with 3d printed parts being too tight.
SAS_SSD_25_DEPTH = 100;
SAS_SSD_25_HEIGHT = 15;
SAS_SSD_25_WIDTH = 70;

SAS_SSD_25_CONNECTOR_DEPTH = 8;

SAS_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_DIAMETER = 3;
SAS_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_WIDTH_OFFSET = 3;

SAS_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_1_DEPTH_OFFSET = 12.5;
SAS_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_2_DEPTH_OFFSET = 89;

SAS_SSD_25_SIDE_MOUNTING_SCREW_HOLE_DIAMETER = SAS_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_DIAMETER;
SAS_SSD_25_SIDE_MOUNTING_SCREW_HOLE_HEIGHT_OFFSET = 1;

SAS_SSD_25_SIDE_MOUNTING_SCREW_HOLE_1_DEPTH_OFFSET = SAS_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_1_DEPTH_OFFSET;
SAS_SSD_25_SIDE_MOUNTING_SCREW_HOLE_2_DEPTH_OFFSET = SAS_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_2_DEPTH_OFFSET;


// NOTE: In practice, it is recommended to increase depth/height/width measurements by at least 1 to
// avoid issues with 3d printed parts being too tight.
SATA_SSD_25_DEPTH = SAS_SSD_25_DEPTH;
SATA_SSD_25_HEIGHT = 7;
SATA_SSD_25_WIDTH = SAS_SSD_25_WIDTH;

SATA_SSD_25_CONNECTOR_DEPTH = SAS_SSD_25_CONNECTOR_DEPTH;

SATA_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_DIAMETER = SAS_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_DIAMETER;
SATA_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_WIDTH_OFFSET = SAS_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_WIDTH_OFFSET;

SATA_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_1_DEPTH_OFFSET = SAS_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_1_DEPTH_OFFSET;
SATA_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_2_DEPTH_OFFSET = SAS_SSD_25_BOTTOM_MOUNTING_SCREW_HOLE_2_DEPTH_OFFSET;

SATA_SSD_25_SIDE_MOUNTING_SCREW_HOLE_DIAMETER = SAS_SSD_25_SIDE_MOUNTING_SCREW_HOLE_DIAMETER;
SATA_SSD_25_SIDE_MOUNTING_SCREW_HOLE_HEIGHT_OFFSET = SAS_SSD_25_SIDE_MOUNTING_SCREW_HOLE_HEIGHT_OFFSET;

SATA_SSD_25_SIDE_MOUNTING_SCREW_HOLE_1_DEPTH_OFFSET = SAS_SSD_25_SIDE_MOUNTING_SCREW_HOLE_1_DEPTH_OFFSET;
SATA_SSD_25_SIDE_MOUNTING_SCREW_HOLE_2_DEPTH_OFFSET = SAS_SSD_25_SIDE_MOUNTING_SCREW_HOLE_2_DEPTH_OFFSET;
