[config]
skip_core_tasks = true
unstable_features = ["CTRL_C_HANDLING"]

[env]
MODEL_NAME = "5ml_test_tubes_tray"
VERSION = { script = ["""
SED=sed; if command -v gsed &> /dev/null; then SED=gsed; fi
echo "v$("${SED}" -n 's@^ *MODEL_VERSION *= *"\\([0-9]\\(\\.[0-9]\\)*\\)"; *$@\\1@p' ./main.scad)"
"""] }

[tasks.gen_dist]
condition = { env_set = [ "MODEL_NAME", "VERSION" ] }
script = """
mkdir -p ./dist
../../scripts/create_model_dist_bundle.sh . ./dist/"${MODEL_NAME}"_"${VERSION}".zip
"""

[tasks.gen_images]
script = """
mkdir -p ./images
../../scripts/gen_model_image.sh ./main.scad ./images/main.png
"""

[tasks.gen_stls]
condition = { env_set = [ "MODEL_NAME", "VERSION" ] }
script = """
mkdir -p ./build
../../scripts/gen_model_stl.sh ./main.scad ./build/"${MODEL_NAME}"_"${VERSION}".stl
"""

[tasks.watch]
script = "../../scripts/watch_in_openscad.sh ./main.scad"
