---
name: Create OpenSCAD model release
run-name: Create OpenSCAD model release from ${{ github.ref_name }} branch

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write

jobs:
  create-openscad-model-release:
    name: Create OpenSCAD model release
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o /tmp/install_rustup.sh && \
            bash -f /tmp/install_rustup.sh -y

      - name: Install Cargo Make
        run: cargo install cargo-make

      - name: Install OpenSCAD
        run: sudo apt-get install --yes openscad

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Extract model name
        run: |
          echo '${{ github.ref_name }}' | \
            cut -f2 -d'/' | \
            xargs -I{} echo MODEL_NAME='{}' >> "${GITHUB_ENV}"

      - name: Extract model release version
        run: |
          echo '${{ github.ref_name }}' | \
            cut -f3 -d'/' | \
            xargs -I{} echo MODEL_RELEASE_VERSION='{}' >> "${GITHUB_ENV}"

      - name: Extract model path
        run: |
          echo 'MODEL_PATH=${{ github.workspace }}/models/${{ env.MODEL_NAME }}' >> "${GITHUB_ENV}"

      - name: Extract model release changelog
        run: |
          '${{ github.workspace }}/utils/get_changelog_section.sh' '${{ env.MODEL_PATH }}/CHANGELOG.md' | \
            xargs -I{} echo MODEL_RELEASE_CHANGELOG_BASE64='{}' >> "${GITHUB_ENV}"

      - name: Render the model
        run: |
          cargo make --cwd '${{ env.MODEL_NAME }}' gen_stls

      - name: Create a release
        run: |
          '${{ github.workspace }}/utils/create_model_github_release.sh' \
            '${{ env.MODEL_PATH }}' \
            '${{ env.MODEL_NAME }}' \
            '${{ env.MODEL_RELEASE_VERSION }}' \
            '${{ env.MODEL_RELEASE_CHANGELOG_BASE64 }}'
