---
name: Create OpenSCAD model release
run-name: Create OpenSCAD model release from ${{ github.ref_name }} branch

on:
  push:
    branches:
      - 'release/**'

permissions:
  contents: write

jobs:
  create-openscad-model-release:
    name: Create OpenSCAD model release
    runs-on: ubuntu-latest
    steps:
      - name: Install Cargo Make
        run: |
          curl -L -o /tmp/cargo_make.zip \
          https://github.com/sagiegurari/cargo-make/releases/download/0.36.4/cargo-make-v0.36.4-x86_64-unknown-linux-musl.zip && \
          unzip -j -d /tmp/cargo_make /tmp/cargo_make.zip && \
          sudo mv /tmp/cargo_make/makers /usr/bin/makers && \
          sudo chown root:root /usr/bin/makers && \
          sudo chmod +x /usr/bin/makers

      - name: Install OpenSCAD
        run: sudo apt-get install --yes openscad

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Extract model name
        run: |
          echo '${{ github.ref_name }}' | \
            cut -f2 -d'/' | \
            xargs -I{} echo MODEL_NAME='{}' >> "${GITHUB_ENV}"

      - name: Extract model release version
        run: |
          echo '${{ github.ref_name }}' | \
            cut -f3 -d'/' | \
            xargs -I{} echo MODEL_RELEASE_VERSION='{}' >> "${GITHUB_ENV}"

      - name: Extract model path
        run: |
          echo 'MODEL_PATH=${{ github.workspace }}/models/${{ env.MODEL_NAME }}' >> "${GITHUB_ENV}"

      - name: Extract model release changelog
        run: |
          '${{ github.workspace }}/utils/get_changelog_section.sh' '${{ env.MODEL_PATH }}/CHANGELOG.md' '${{ env.MODEL_RELEASE_VERSION }}' | \
            base64 | \
            xargs -I{} echo MODEL_RELEASE_CHANGELOG_BASE64='{}' >> "${GITHUB_ENV}"

      - name: Render the model
        run: |
          makers --cwd '${{ env.MODEL_PATH }}' gen_stls

      - name: Create a release
        run: |
          '${{ github.workspace }}/utils/create_model_github_release.sh' \
            '${{ env.MODEL_PATH }}' \
            '${{ env.MODEL_NAME }}' \
            '${{ env.MODEL_RELEASE_VERSION }}' \
            '${{ env.MODEL_RELEASE_CHANGELOG_BASE64 }}'
